### ISSUE TITLE
Size uses numbers and not size strings

### ISSUE THREAD

**Issue by DW01** [samclarke/SCEditor-MyBB#3]
Using size 1 text in the MyBB plugin literally places [size=1][/size] in the textarea which MyBB interprets differently from its own equivalent size strings -- the plugin should use [size=xx-small], [size=x-small], [size=small] etc etc. instead of numerals.

**Comment by samclarke** [comment]
Thanks for reporting. Should now be fixed.

**Comment by DW01** [comment]
Bug still seems to happen in source mode, but when adding these tags from normal mode everything works as it should.

**Comment by samclarke** [comment]
Ah yes I missed that one. I've updated it now so it should all work.
